name: streamingcommunity_scraper
description: Dart package to scrape Italian streaming website streamingcommunity
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  beautiful_soup_dart: ^0.3.0
  http: ^1.2.2
  puppeteer: ^3.12.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
